### PR TITLE
[Cache] Adding isHit()

### PR DESCRIPTION
**Pull request by dragoonis**

### CODE REVIEW

**Comment by AmyStephen** [comment]
+1 WTG @dragoonis

**Comment by philsturgeon** [comment]
:+1:

**Comment by dongilbert** [comment]
The shortness of the method name leaves a little to be desired. It's not clear what it does just by itself. I don't see how it could be seen as a replacement for `isValid`. If the purpose of `isHit` is just that it `Confirms if the cache item exists in the cache`, then `isInCache` would be a better name.

However, I'm of the mind that the a `Cache\Item` should really have no concept of the `Cache\Pool` or know that it exists. It should have methods to set and retrieve it's value, and to determine whether or not it is expired, but not much else. For an item to determine whether or not it already exists in the cache violates single responsibility. The item should be responsible for it's own interactions and the `Cache\Pool` should determine whether or not it contains any specific item.

I'm sure that part of the cache discussion was already beat to death in the time of my predecessor, but I missed out on it. If someone has links they could share pointing these out, it would be more convenient than me reading a years worth of mailing list threads.

**Comment by dragoonis** [comment]
On Wed, Jun 26, 2013 at 9:33 PM, Don Gilbert notifications@github.comwrote:

> The shortness of the method name leaves a little to be desired. It's not
> clear what it does just by itself. I don't see how it could be seen as a
> replacement for isValid. If the purpose of isHit is just that it Confirms
> if the cache item exists in the cache, then isInCache would be a better
> name.
> 
> However, I'm of the mind that the a Cache\Item should really have no
> concept of the Cache\Pool or know that it exists.

What you just described is the Weak proposal and the majority of the group
voted for Strong, we must move on.

> It should have methods to set and retrieve it's value, and to determine
> whether or not it is expired, but not much else. For an item to determine
> whether or not it already exists in the cache violates single
> responsibility. The item should be responsible for it's own interactions
> and the Cache\Pool should determine whether or not it contains any
> specific item.

Here's an example implementation of the weak cache proposal, it shows you
how you evaluate 'isInCache' while you get the value in the same
transaction so that isHit() is identified at the same time as get().

https://github.com/ppi/ppi-cache-module/blob/master/Cache/Driver/RedisCache.php#L36

**Comment by dongilbert** [comment]
Ok. I guess I misunderstood strong item vs weak item then as well, because I voted strong item. Weak item to me meant value object that didn't even handle setting it's own value, and all interaction with it went through the Pool, which I don't like. I also don't like what you are explaining as "Strong Item" in that an Item controls everything. I see it as two extremes, neither of which works all that well.

But as I said, it was probably all discussed prior to my coming on board the FIG for Joomla, but it would be nice for some discussion links and explanations so I can review and get up to speed with the rest of the voting members.

**Comment by tedivm** [comment]
@dongilbert - the cache item _has_ to know if it exists or not, which is the same both for the strong and weak proposals. Your assessment was correct- the weak proposal meant that the value object was simply an immutable return wrapper, and the strong proposal means that the pool controls it's actions and the item controls it's own. 

There is a big reason why the isHIt (or isMiss, or isValid) functions have to exist in the Item though- it prevents race conditions. If someone calls isHit on the pool, and then pulls the Item out of the pool, there's a space between the isHit and the Item creation where a separate process could remove the item from the cache. If that were to happen the code would act like it had a proper value when it in fact does not. By making the item responsible for knowing it's current state (with either the weak or strong proposal) this problem is removed.

**Comment by dragoonis** [comment]
On Thu, Jun 27, 2013 at 7:30 AM, Robert Hafner notifications@github.comwrote:

> @dongilbert https://github.com/dongilbert - the cache item _has_ to
> know if it exists or not, which is the same both for the strong and weak
> proposals. Your assessment was correct- the weak proposal meant that the
> value object was simply an immutable return wrapper, and the strong
> proposal means that the pool controls it's actions and the item controls
> it's own.
> 
> There is a big reason why the isHIt (or isMiss, or isValid) functions have
> to exist in the Item though- it prevents race conditions. If someone calls
> isHit on the pool, and then pulls the Item out of the pool, there's a space
> between the isHit and the Item creation where a separate process could
> remove the item from the cache. If that were to happen the code would act
> like it had a proper value when it in fact does not. By making the item
> responsible for knowing it's current state (with either the weak or strong
> proposal) this problem is removed.

To add to what Robert said: this is why I in the PPI Framework cache module
i linked to above does things in a Transaction to ensure there's no race
conditions

**Comment by Crell** [comment]
isHit() seems to be what the general consensus was, so let's run with that.  Paul and Robert already covered why it needs to be where it is in a Repository model.

**Pull request merged**
